<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'dial_code' => '+93', 'currency_code' => 'AFN', 'currency_name' => 'Afghan Afghani'],
            ['name' => 'Albania', 'code' => 'AL', 'dial_code' => '+355', 'currency_code' => 'ALL', 'currency_name' => 'Albanian Lek'],
            ['name' => 'Algeria', 'code' => 'DZ', 'dial_code' => '+213', 'currency_code' => 'DZD', 'currency_name' => 'Algerian Dinar'],
            ['name' => 'Andorra', 'code' => 'AD', 'dial_code' => '+376', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Angola', 'code' => 'AO', 'dial_code' => '+244', 'currency_code' => 'AOA', 'currency_name' => 'Angolan Kwanza'],
            ['name' => 'Argentina', 'code' => 'AR', 'dial_code' => '+54', 'currency_code' => 'ARS', 'currency_name' => 'Argentine Peso'],
            ['name' => 'Armenia', 'code' => 'AM', 'dial_code' => '+374', 'currency_code' => 'AMD', 'currency_name' => 'Armenian Dram'],
            ['name' => 'Australia', 'code' => 'AU', 'dial_code' => '+61', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar'],
            ['name' => 'Austria', 'code' => 'AT', 'dial_code' => '+43', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'dial_code' => '+994', 'currency_code' => 'AZN', 'currency_name' => 'Azerbaijani Manat'],
            ['name' => 'Bahamas', 'code' => 'BS', 'dial_code' => '+1', 'currency_code' => 'BSD', 'currency_name' => 'Bahamian Dollar'],
            ['name' => 'Bahrain', 'code' => 'BH', 'dial_code' => '+973', 'currency_code' => 'BHD', 'currency_name' => 'Bahraini Dinar'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'dial_code' => '+880', 'currency_code' => 'BDT', 'currency_name' => 'Bangladeshi Taka'],
            ['name' => 'Barbados', 'code' => 'BB', 'dial_code' => '+1', 'currency_code' => 'BBD', 'currency_name' => 'Barbadian Dollar'],
            ['name' => 'Belarus', 'code' => 'BY', 'dial_code' => '+375', 'currency_code' => 'BYN', 'currency_name' => 'Belarusian Ruble'],
            ['name' => 'Belgium', 'code' => 'BE', 'dial_code' => '+32', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Belize', 'code' => 'BZ', 'dial_code' => '+501', 'currency_code' => 'BZD', 'currency_name' => 'Belize Dollar'],
            ['name' => 'Benin', 'code' => 'BJ', 'dial_code' => '+229', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc'],
            ['name' => 'Bhutan', 'code' => 'BT', 'dial_code' => '+975', 'currency_code' => 'BTN', 'currency_name' => 'Bhutanese Ngultrum'],
            ['name' => 'Bolivia', 'code' => 'BO', 'dial_code' => '+591', 'currency_code' => 'BOB', 'currency_name' => 'Bolivian Boliviano'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'dial_code' => '+387', 'currency_code' => 'BAM', 'currency_name' => 'Bosnia-Herzegovina Convertible Mark'],
            ['name' => 'Botswana', 'code' => 'BW', 'dial_code' => '+267', 'currency_code' => 'BWP', 'currency_name' => 'Botswanan Pula'],
            ['name' => 'Brazil', 'code' => 'BR', 'dial_code' => '+55', 'currency_code' => 'BRL', 'currency_name' => 'Brazilian Real'],
            ['name' => 'Brunei', 'code' => 'BN', 'dial_code' => '+673', 'currency_code' => 'BND', 'currency_name' => 'Brunei Dollar'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'dial_code' => '+359', 'currency_code' => 'BGN', 'currency_name' => 'Bulgarian Lev'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'dial_code' => '+226', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc'],
            ['name' => 'Burundi', 'code' => 'BI', 'dial_code' => '+257', 'currency_code' => 'BIF', 'currency_name' => 'Burundian Franc'],
            ['name' => 'Cabo Verde', 'code' => 'CV', 'dial_code' => '+238', 'currency_code' => 'CVE', 'currency_name' => 'Cape Verdean Escudo'],
            ['name' => 'Cambodia', 'code' => 'KH', 'dial_code' => '+855', 'currency_code' => 'KHR', 'currency_name' => 'Cambodian Riel'],
            ['name' => 'Cameroon', 'code' => 'CM', 'dial_code' => '+237', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc'],
            ['name' => 'Canada', 'code' => 'CA', 'dial_code' => '+1', 'currency_code' => 'CAD', 'currency_name' => 'Canadian Dollar'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'dial_code' => '+236', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc'],
            ['name' => 'Chad', 'code' => 'TD', 'dial_code' => '+235', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc'],
            ['name' => 'Chile', 'code' => 'CL', 'dial_code' => '+56', 'currency_code' => 'CLP', 'currency_name' => 'Chilean Peso'],
            ['name' => 'China', 'code' => 'CN', 'dial_code' => '+86', 'currency_code' => 'CNY', 'currency_name' => 'Chinese Yuan'],
            ['name' => 'Colombia', 'code' => 'CO', 'dial_code' => '+57', 'currency_code' => 'COP', 'currency_name' => 'Colombian Peso'],
            ['name' => 'Comoros', 'code' => 'KM', 'dial_code' => '+269', 'currency_code' => 'KMF', 'currency_name' => 'Comorian Franc'],
            ['name' => 'Congo', 'code' => 'CG', 'dial_code' => '+242', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'dial_code' => '+506', 'currency_code' => 'CRC', 'currency_name' => 'Costa Rican Colón'],
            ['name' => 'Croatia', 'code' => 'HR', 'dial_code' => '+385', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Cuba', 'code' => 'CU', 'dial_code' => '+53', 'currency_code' => 'CUP', 'currency_name' => 'Cuban Peso'],
            ['name' => 'Cyprus', 'code' => 'CY', 'dial_code' => '+357', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'dial_code' => '+420', 'currency_code' => 'CZK', 'currency_name' => 'Czech Koruna'],
            ['name' => 'Denmark', 'code' => 'DK', 'dial_code' => '+45', 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'dial_code' => '+253', 'currency_code' => 'DJF', 'currency_name' => 'Djiboutian Franc'],
            ['name' => 'Dominica', 'code' => 'DM', 'dial_code' => '+1', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'dial_code' => '+1', 'currency_code' => 'DOP', 'currency_name' => 'Dominican Peso'],
            ['name' => 'Ecuador', 'code' => 'EC', 'dial_code' => '+593', 'currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['name' => 'Egypt', 'code' => 'EG', 'dial_code' => '+20', 'currency_code' => 'EGP', 'currency_name' => 'Egyptian Pound'],
            ['name' => 'El Salvador', 'code' => 'SV', 'dial_code' => '+503', 'currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'dial_code' => '+240', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc'],
            ['name' => 'Eritrea', 'code' => 'ER', 'dial_code' => '+291', 'currency_code' => 'ERN', 'currency_name' => 'Eritrean Nakfa'],
            ['name' => 'Estonia', 'code' => 'EE', 'dial_code' => '+372', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Eswatini', 'code' => 'SZ', 'dial_code' => '+268', 'currency_code' => 'SZL', 'currency_name' => 'Swazi Lilangeni'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'dial_code' => '+251', 'currency_code' => 'ETB', 'currency_name' => 'Ethiopian Birr'],
            ['name' => 'Fiji', 'code' => 'FJ', 'dial_code' => '+679', 'currency_code' => 'FJD', 'currency_name' => 'Fijian Dollar'],
            ['name' => 'Finland', 'code' => 'FI', 'dial_code' => '+358', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'France', 'code' => 'FR', 'dial_code' => '+33', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Gabon', 'code' => 'GA', 'dial_code' => '+241', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc'],
            ['name' => 'Gambia', 'code' => 'GM', 'dial_code' => '+220', 'currency_code' => 'GMD', 'currency_name' => 'Gambian Dalasi'],
            ['name' => 'Georgia', 'code' => 'GE', 'dial_code' => '+995', 'currency_code' => 'GEL', 'currency_name' => 'Georgian Lari'],
            ['name' => 'Germany', 'code' => 'DE', 'dial_code' => '+49', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Ghana', 'code' => 'GH', 'dial_code' => '+233', 'currency_code' => 'GHS', 'currency_name' => 'Ghanaian Cedi'],
            ['name' => 'Greece', 'code' => 'GR', 'dial_code' => '+30', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Grenada', 'code' => 'GD', 'dial_code' => '+1', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar'],
            ['name' => 'Guatemala', 'code' => 'GT', 'dial_code' => '+502', 'currency_code' => 'GTQ', 'currency_name' => 'Guatemalan Quetzal'],
            ['name' => 'Guinea', 'code' => 'GN', 'dial_code' => '+224', 'currency_code' => 'GNF', 'currency_name' => 'Guinean Franc'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'dial_code' => '+245', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc'],
            ['name' => 'Guyana', 'code' => 'GY', 'dial_code' => '+592', 'currency_code' => 'GYD', 'currency_name' => 'Guyanaese Dollar'],
            ['name' => 'Haiti', 'code' => 'HT', 'dial_code' => '+509', 'currency_code' => 'HTG', 'currency_name' => 'Haitian Gourde'],
            ['name' => 'Honduras', 'code' => 'HN', 'dial_code' => '+504', 'currency_code' => 'HNL', 'currency_name' => 'Honduran Lempira'],
            ['name' => 'Hungary', 'code' => 'HU', 'dial_code' => '+36', 'currency_code' => 'HUF', 'currency_name' => 'Hungarian Forint'],
            ['name' => 'Iceland', 'code' => 'IS', 'dial_code' => '+354', 'currency_code' => 'ISK', 'currency_name' => 'Icelandic Króna'],
            ['name' => 'India', 'code' => 'IN', 'dial_code' => '+91', 'currency_code' => 'INR', 'currency_name' => 'Indian Rupee'],
            ['name' => 'Indonesia', 'code' => 'ID', 'dial_code' => '+62', 'currency_code' => 'IDR', 'currency_name' => 'Indonesian Rupiah'],
            ['name' => 'Iran', 'code' => 'IR', 'dial_code' => '+98', 'currency_code' => 'IRR', 'currency_name' => 'Iranian Rial'],
            ['name' => 'Iraq', 'code' => 'IQ', 'dial_code' => '+964', 'currency_code' => 'IQD', 'currency_name' => 'Iraqi Dinar'],
            ['name' => 'Ireland', 'code' => 'IE', 'dial_code' => '+353', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Israel', 'code' => 'IL', 'dial_code' => '+972', 'currency_code' => 'ILS', 'currency_name' => 'Israeli New Shekel'],
            ['name' => 'Italy', 'code' => 'IT', 'dial_code' => '+39', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Jamaica', 'code' => 'JM', 'dial_code' => '+1', 'currency_code' => 'JMD', 'currency_name' => 'Jamaican Dollar'],
            ['name' => 'Japan', 'code' => 'JP', 'dial_code' => '+81', 'currency_code' => 'JPY', 'currency_name' => 'Japanese Yen'],
            ['name' => 'Jordan', 'code' => 'JO', 'dial_code' => '+962', 'currency_code' => 'JOD', 'currency_name' => 'Jordanian Dinar'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'dial_code' => '+7', 'currency_code' => 'KZT', 'currency_name' => 'Kazakhstani Tenge'],
            ['name' => 'Kenya', 'code' => 'KE', 'dial_code' => '+254', 'currency_code' => 'KES', 'currency_name' => 'Kenyan Shilling'],
            ['name' => 'Kiribati', 'code' => 'KI', 'dial_code' => '+686', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar'],
            ['name' => 'Kuwait', 'code' => 'KW', 'dial_code' => '+965', 'currency_code' => 'KWD', 'currency_name' => 'Kuwaiti Dinar'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'dial_code' => '+996', 'currency_code' => 'KGS', 'currency_name' => 'Kyrgystani Som'],
            ['name' => 'Laos', 'code' => 'LA', 'dial_code' => '+856', 'currency_code' => 'LAK', 'currency_name' => 'Laotian Kip'],
            ['name' => 'Latvia', 'code' => 'LV', 'dial_code' => '+371', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Lebanon', 'code' => 'LB', 'dial_code' => '+961', 'currency_code' => 'LBP', 'currency_name' => 'Lebanese Pound'],
            ['name' => 'Lesotho', 'code' => 'LS', 'dial_code' => '+266', 'currency_code' => 'LSL', 'currency_name' => 'Lesotho Loti'],
            ['name' => 'Liberia', 'code' => 'LR', 'dial_code' => '+231', 'currency_code' => 'LRD', 'currency_name' => 'Liberian Dollar'],
            ['name' => 'Libya', 'code' => 'LY', 'dial_code' => '+218', 'currency_code' => 'LYD', 'currency_name' => 'Libyan Dinar'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'dial_code' => '+423', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc'],
            ['name' => 'Lithuania', 'code' => 'LT', 'dial_code' => '+370', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'dial_code' => '+352', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Madagascar', 'code' => 'MG', 'dial_code' => '+261', 'currency_code' => 'MGA', 'currency_name' => 'Malagasy Ariary'],
            ['name' => 'Malawi', 'code' => 'MW', 'dial_code' => '+265', 'currency_code' => 'MWK', 'currency_name' => 'Malawian Kwacha'],
            ['name' => 'Malaysia', 'code' => 'MY', 'dial_code' => '+60', 'currency_code' => 'MYR', 'currency_name' => 'Malaysian Ringgit'],
            ['name' => 'Maldives', 'code' => 'MV', 'dial_code' => '+960', 'currency_code' => 'MVR', 'currency_name' => 'Maldivian Rufiyaa'],
            ['name' => 'Mali', 'code' => 'ML', 'dial_code' => '+223', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc'],
            ['name' => 'Malta', 'code' => 'MT', 'dial_code' => '+356', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'dial_code' => '+692', 'currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['name' => 'Mauritania', 'code' => 'MR', 'dial_code' => '+222', 'currency_code' => 'MRU', 'currency_name' => 'Mauritanian Ouguiya'],
            ['name' => 'Mauritius', 'code' => 'MU', 'dial_code' => '+230', 'currency_code' => 'MUR', 'currency_name' => 'Mauritian Rupee'],
            ['name' => 'Mexico', 'code' => 'MX', 'dial_code' => '+52', 'currency_code' => 'MXN', 'currency_name' => 'Mexican Peso'],
            ['name' => 'Micronesia', 'code' => 'FM', 'dial_code' => '+691', 'currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['name' => 'Moldova', 'code' => 'MD', 'dial_code' => '+373', 'currency_code' => 'MDL', 'currency_name' => 'Moldovan Leu'],
            ['name' => 'Monaco', 'code' => 'MC', 'dial_code' => '+377', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Mongolia', 'code' => 'MN', 'dial_code' => '+976', 'currency_code' => 'MNT', 'currency_name' => 'Mongolian Tugrik'],
            ['name' => 'Montenegro', 'code' => 'ME', 'dial_code' => '+382', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Morocco', 'code' => 'MA', 'dial_code' => '+212', 'currency_code' => 'MAD', 'currency_name' => 'Moroccan Dirham'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'dial_code' => '+258', 'currency_code' => 'MZN', 'currency_name' => 'Mozambican Metical'],
            ['name' => 'Myanmar', 'code' => 'MM', 'dial_code' => '+95', 'currency_code' => 'MMK', 'currency_name' => 'Myanmar Kyat'],
            ['name' => 'Namibia', 'code' => 'NA', 'dial_code' => '+264', 'currency_code' => 'NAD', 'currency_name' => 'Namibian Dollar'],
            ['name' => 'Nauru', 'code' => 'NR', 'dial_code' => '+674', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar'],
            ['name' => 'Nepal', 'code' => 'NP', 'dial_code' => '+977', 'currency_code' => 'NPR', 'currency_name' => 'Nepalese Rupee'],
            ['name' => 'Netherlands', 'code' => 'NL', 'dial_code' => '+31', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'dial_code' => '+64', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'dial_code' => '+505', 'currency_code' => 'NIO', 'currency_name' => 'Nicaraguan Córdoba'],
            ['name' => 'Niger', 'code' => 'NE', 'dial_code' => '+227', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc'],
            ['name' => 'Nigeria', 'code' => 'NG', 'dial_code' => '+234', 'currency_code' => 'NGN', 'currency_name' => 'Nigerian Naira'],
            ['name' => 'North Korea', 'code' => 'KP', 'dial_code' => '+850', 'currency_code' => 'KPW', 'currency_name' => 'North Korean Won'],
            ['name' => 'North Macedonia', 'code' => 'MK', 'dial_code' => '+389', 'currency_code' => 'MKD', 'currency_name' => 'Macedonian Denar'],
            ['name' => 'Norway', 'code' => 'NO', 'dial_code' => '+47', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone'],
            ['name' => 'Oman', 'code' => 'OM', 'dial_code' => '+968', 'currency_code' => 'OMR', 'currency_name' => 'Omani Rial'],
            ['name' => 'Pakistan', 'code' => 'PK', 'dial_code' => '+92', 'currency_code' => 'PKR', 'currency_name' => 'Pakistani Rupee'],
            ['name' => 'Palau', 'code' => 'PW', 'dial_code' => '+680', 'currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['name' => 'Palestine', 'code' => 'PS', 'dial_code' => '+970', 'currency_code' => 'ILS', 'currency_name' => 'Israeli New Shekel'],
            ['name' => 'Panama', 'code' => 'PA', 'dial_code' => '+507', 'currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'dial_code' => '+675', 'currency_code' => 'PGK', 'currency_name' => 'Papua New Guinean Kina'],
            ['name' => 'Paraguay', 'code' => 'PY', 'dial_code' => '+595', 'currency_code' => 'PYG', 'currency_name' => 'Paraguayan Guarani'],
            ['name' => 'Peru', 'code' => 'PE', 'dial_code' => '+51', 'currency_code' => 'PEN', 'currency_name' => 'Peruvian Sol'],
            ['name' => 'Philippines', 'code' => 'PH', 'dial_code' => '+63', 'currency_code' => 'PHP', 'currency_name' => 'Philippine Peso'],
            ['name' => 'Poland', 'code' => 'PL', 'dial_code' => '+48', 'currency_code' => 'PLN', 'currency_name' => 'Polish Zloty'],
            ['name' => 'Portugal', 'code' => 'PT', 'dial_code' => '+351', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Qatar', 'code' => 'QA', 'dial_code' => '+974', 'currency_code' => 'QAR', 'currency_name' => 'Qatari Rial'],
            ['name' => 'Romania', 'code' => 'RO', 'dial_code' => '+40', 'currency_code' => 'RON', 'currency_name' => 'Romanian Leu'],
            ['name' => 'Russia', 'code' => 'RU', 'dial_code' => '+7', 'currency_code' => 'RUB', 'currency_name' => 'Russian Ruble'],
            ['name' => 'Rwanda', 'code' => 'RW', 'dial_code' => '+250', 'currency_code' => 'RWF', 'currency_name' => 'Rwandan Franc'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'dial_code' => '+1', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'dial_code' => '+1', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'dial_code' => '+1', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar'],
            ['name' => 'Samoa', 'code' => 'WS', 'dial_code' => '+685', 'currency_code' => 'WST', 'currency_name' => 'Samoan Tala'],
            ['name' => 'San Marino', 'code' => 'SM', 'dial_code' => '+378', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'São Tomé and Príncipe', 'code' => 'ST', 'dial_code' => '+239', 'currency_code' => 'STN', 'currency_name' => 'São Tomé and Príncipe Dobra'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'dial_code' => '+966', 'currency_code' => 'SAR', 'currency_name' => 'Saudi Riyal'],
            ['name' => 'Senegal', 'code' => 'SN', 'dial_code' => '+221', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc'],
            ['name' => 'Serbia', 'code' => 'RS', 'dial_code' => '+381', 'currency_code' => 'RSD', 'currency_name' => 'Serbian Dinar'],
            ['name' => 'Seychelles', 'code' => 'SC', 'dial_code' => '+248', 'currency_code' => 'SCR', 'currency_name' => 'Seychellois Rupee'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'dial_code' => '+232', 'currency_code' => 'SLL', 'currency_name' => 'Sierra Leonean Leone'],
            ['name' => 'Singapore', 'code' => 'SG', 'dial_code' => '+65', 'currency_code' => 'SGD', 'currency_name' => 'Singapore Dollar'],
            ['name' => 'Slovakia', 'code' => 'SK', 'dial_code' => '+421', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Slovenia', 'code' => 'SI', 'dial_code' => '+386', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'dial_code' => '+677', 'currency_code' => 'SBD', 'currency_name' => 'Solomon Islands Dollar'],
            ['name' => 'Somalia', 'code' => 'SO', 'dial_code' => '+252', 'currency_code' => 'SOS', 'currency_name' => 'Somali Shilling'],
            ['name' => 'South Africa', 'code' => 'ZA', 'dial_code' => '+27', 'currency_code' => 'ZAR', 'currency_name' => 'South African Rand'],
            ['name' => 'South Korea', 'code' => 'KR', 'dial_code' => '+82', 'currency_code' => 'KRW', 'currency_name' => 'South Korean Won'],
            ['name' => 'South Sudan', 'code' => 'SS', 'dial_code' => '+211', 'currency_code' => 'SSP', 'currency_name' => 'South Sudanese Pound'],
            ['name' => 'Spain', 'code' => 'ES', 'dial_code' => '+34', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'dial_code' => '+94', 'currency_code' => 'LKR', 'currency_name' => 'Sri Lankan Rupee'],
            ['name' => 'Sudan', 'code' => 'SD', 'dial_code' => '+249', 'currency_code' => 'SDG', 'currency_name' => 'Sudanese Pound'],
            ['name' => 'Suriname', 'code' => 'SR', 'dial_code' => '+597', 'currency_code' => 'SRD', 'currency_name' => 'Surinamese Dollar'],
            ['name' => 'Sweden', 'code' => 'SE', 'dial_code' => '+46', 'currency_code' => 'SEK', 'currency_name' => 'Swedish Krona'],
            ['name' => 'Switzerland', 'code' => 'CH', 'dial_code' => '+41', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc'],
            ['name' => 'Syria', 'code' => 'SY', 'dial_code' => '+963', 'currency_code' => 'SYP', 'currency_name' => 'Syrian Pound'],
            ['name' => 'Taiwan', 'code' => 'TW', 'dial_code' => '+886', 'currency_code' => 'TWD', 'currency_name' => 'New Taiwan Dollar'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'dial_code' => '+992', 'currency_code' => 'TJS', 'currency_name' => 'Tajikistani Somoni'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'dial_code' => '+255', 'currency_code' => 'TZS', 'currency_name' => 'Tanzanian Shilling'],
            ['name' => 'Thailand', 'code' => 'TH', 'dial_code' => '+66', 'currency_code' => 'THB', 'currency_name' => 'Thai Baht'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'dial_code' => '+670', 'currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['name' => 'Togo', 'code' => 'TG', 'dial_code' => '+228', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc'],
            ['name' => 'Tonga', 'code' => 'TO', 'dial_code' => '+676', 'currency_code' => 'TOP', 'currency_name' => 'Tongan Paʻanga'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'dial_code' => '+1', 'currency_code' => 'TTD', 'currency_name' => 'Trinidad and Tobago Dollar'],
            ['name' => 'Tunisia', 'code' => 'TN', 'dial_code' => '+216', 'currency_code' => 'TND', 'currency_name' => 'Tunisian Dinar'],
            ['name' => 'Turkey', 'code' => 'TR', 'dial_code' => '+90', 'currency_code' => 'TRY', 'currency_name' => 'Turkish Lira'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'dial_code' => '+993', 'currency_code' => 'TMT', 'currency_name' => 'Turkmenistani Manat'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'dial_code' => '+688', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar'],
            ['name' => 'Uganda', 'code' => 'UG', 'dial_code' => '+256', 'currency_code' => 'UGX', 'currency_name' => 'Ugandan Shilling'],
            ['name' => 'Ukraine', 'code' => 'UA', 'dial_code' => '+380', 'currency_code' => 'UAH', 'currency_name' => 'Ukrainian Hryvnia'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'dial_code' => '+971', 'currency_code' => 'AED', 'currency_name' => 'UAE Dirham'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'dial_code' => '+44', 'currency_code' => 'GBP', 'currency_name' => 'British Pound'],
            ['name' => 'United States', 'code' => 'US', 'dial_code' => '+1', 'currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['name' => 'Uruguay', 'code' => 'UY', 'dial_code' => '+598', 'currency_code' => 'UYU', 'currency_name' => 'Uruguayan Peso'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'dial_code' => '+998', 'currency_code' => 'UZS', 'currency_name' => 'Uzbekistani Som'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'dial_code' => '+678', 'currency_code' => 'VUV', 'currency_name' => 'Vanuatu Vatu'],
            ['name' => 'Vatican City', 'code' => 'VA', 'dial_code' => '+39', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Venezuela', 'code' => 'VE', 'dial_code' => '+58', 'currency_code' => 'VES', 'currency_name' => 'Venezuelan Bolívar'],
            ['name' => 'Vietnam', 'code' => 'VN', 'dial_code' => '+84', 'currency_code' => 'VND', 'currency_name' => 'Vietnamese Dong'],
            ['name' => 'Yemen', 'code' => 'YE', 'dial_code' => '+967', 'currency_code' => 'YER', 'currency_name' => 'Yemeni Rial'],
            ['name' => 'Zambia', 'code' => 'ZM', 'dial_code' => '+260', 'currency_code' => 'ZMW', 'currency_name' => 'Zambian Kwacha'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'dial_code' => '+263', 'currency_code' => 'ZWL', 'currency_name' => 'Zimbabwean Dollar'],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['code' => $country['code']],
                $country,
            );
        }
    }
}
