<?php

declare(strict_types=1);

namespace App\Domain\Privacy\Services;

use App\Domain\Privacy\Enums\ProofType;
use App\Domain\Privacy\ValueObjects\ZkProof;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use RuntimeException;

/**
 * On-chain ZK proof verification service.
 *
 * Submits Groth16 proofs to deployed Solidity verifier contracts via JSON-RPC.
 * Each ProofType maps to a deployed verifier contract address. The contracts
 * are generated by snarkjs from the circuit's verification key:
 *   snarkjs zkey export solidityverifier circuit.zkey verifier.sol
 *
 * Verification flow:
 * 1. Decode proof into (a, b, c) Groth16 curve points
 * 2. Encode as Solidity verifyProof(uint[2] a, uint[2][2] b, uint[2] c, uint[] input) call
 * 3. Submit eth_call to the verifier contract
 * 4. Decode boolean result
 */
class OnChainVerifierService
{
    /** @var array<string, string> */
    private readonly array $verifierAddresses;

    private readonly string $defaultRpcUrl;

    public function __construct()
    {
        /** @var array<string, string> $addresses */
        $addresses = (array) config('privacy.zk.verifier_addresses', []);
        $this->verifierAddresses = $addresses;
        $this->defaultRpcUrl = (string) config('privacy.zk.rpc_url', '');
    }

    /**
     * Verify a ZK proof on-chain via the Solidity verifier contract.
     *
     * @return array{verified: bool, tx_hash: string|null, gas_used: int, chain: string}
     */
    public function verifyOnChain(ZkProof $proof, ?string $rpcUrl = null): array
    {
        $verifierAddress = $this->getVerifierAddress($proof->type);
        $rpc = $rpcUrl ?? $this->defaultRpcUrl;

        if ($rpc === '') {
            Log::warning('On-chain verification skipped: no RPC URL configured', [
                'proof_type' => $proof->type->value,
            ]);

            return $this->fallbackVerification($proof);
        }

        Log::info('Submitting ZK proof for on-chain verification', [
            'proof_type'       => $proof->type->value,
            'verifier_address' => $verifierAddress,
        ]);

        $callData = $this->encodeVerifyProofCall($proof);

        $response = Http::timeout(30)
            ->post($rpc, [
                'jsonrpc' => '2.0',
                'id'      => 1,
                'method'  => 'eth_call',
                'params'  => [
                    [
                        'to'   => $verifierAddress,
                        'data' => $callData,
                    ],
                    'latest',
                ],
            ]);

        if (! $response->successful()) {
            Log::error('On-chain verification RPC call failed', [
                'status' => $response->status(),
            ]);

            return [
                'verified' => false,
                'tx_hash'  => null,
                'gas_used' => 0,
                'chain'    => $this->detectChain($rpc),
            ];
        }

        $data = $response->json();

        if (isset($data['error'])) {
            Log::error('On-chain verification returned error', [
                'error' => $data['error'],
            ]);

            return [
                'verified' => false,
                'tx_hash'  => null,
                'gas_used' => 0,
                'chain'    => $this->detectChain($rpc),
            ];
        }

        $result = (string) ($data['result'] ?? '0x0');
        $verified = $this->decodeBoolResult($result);

        Log::info('On-chain ZK proof verification result', [
            'proof_type' => $proof->type->value,
            'verified'   => $verified,
        ]);

        return [
            'verified' => $verified,
            'tx_hash'  => null, // eth_call doesn't create tx
            'gas_used' => $this->estimateGas($rpc, $verifierAddress, $callData),
            'chain'    => $this->detectChain($rpc),
        ];
    }

    /**
     * Estimate gas cost for on-chain verification.
     */
    public function estimateVerificationGas(ZkProof $proof, ?string $rpcUrl = null): int
    {
        $verifierAddress = $this->getVerifierAddress($proof->type);
        $rpc = $rpcUrl ?? $this->defaultRpcUrl;

        if ($rpc === '') {
            // Groth16 verification typically costs ~230k gas
            return 230000;
        }

        $callData = $this->encodeVerifyProofCall($proof);

        return $this->estimateGas($rpc, $verifierAddress, $callData);
    }

    /**
     * Get the deployed verifier contract address for a proof type.
     */
    public function getVerifierAddress(ProofType $type): string
    {
        return $this->verifierAddresses[$type->value]
            ?? '0x' . str_repeat('0', 40);
    }

    /**
     * Check if a verifier contract is deployed for a proof type.
     */
    public function isVerifierDeployed(ProofType $type): bool
    {
        $address = $this->getVerifierAddress($type);

        return $address !== '0x' . str_repeat('0', 40) && $address !== '';
    }

    /**
     * Get deployment status for all verifier contracts.
     *
     * @return array<string, array{address: string, deployed: bool}>
     */
    public function getDeploymentStatus(): array
    {
        $status = [];

        foreach (ProofType::cases() as $type) {
            $address = $this->getVerifierAddress($type);
            $status[$type->value] = [
                'address'  => $address,
                'deployed' => $this->isVerifierDeployed($type),
            ];
        }

        return $status;
    }

    /**
     * Encode Groth16 proof for Solidity verifyProof() call.
     *
     * Solidity function signature:
     *   function verifyProof(uint[2] a, uint[2][2] b, uint[2] c, uint[] input) returns (bool)
     * Selector: 0x43753b4d
     */
    private function encodeVerifyProofCall(ZkProof $proof): string
    {
        $decodedProof = base64_decode($proof->proof, true);
        if ($decodedProof === false) {
            throw new RuntimeException('Invalid proof encoding');
        }

        /** @var array<string, mixed> $proofData */
        $proofData = json_decode($decodedProof, true, 512, JSON_THROW_ON_ERROR);

        // Extract Groth16 proof points (a, b, c)
        $piA = $proofData['pi_a'] ?? ['0', '0'];
        $piB = $proofData['pi_b'] ?? [['0', '0'], ['0', '0']];
        $piC = $proofData['pi_c'] ?? ['0', '0'];

        // Function selector for verifyProof
        $selector = '43753b4d';

        // ABI encode: a[2], b[2][2], c[2], inputs
        // Uses bcmath for 256-bit field elements that exceed PHP int range
        $encoded = $selector;

        // Encode a[0], a[1]
        $encoded .= $this->encodeUint256((string) ($piA[0] ?? '0'));
        $encoded .= $this->encodeUint256((string) ($piA[1] ?? '0'));

        // Encode b[0][0], b[0][1], b[1][0], b[1][1]
        $encoded .= $this->encodeUint256((string) ($piB[0][0] ?? '0'));
        $encoded .= $this->encodeUint256((string) ($piB[0][1] ?? '0'));
        $encoded .= $this->encodeUint256((string) ($piB[1][0] ?? '0'));
        $encoded .= $this->encodeUint256((string) ($piB[1][1] ?? '0'));

        // Encode c[0], c[1]
        $encoded .= $this->encodeUint256((string) ($piC[0] ?? '0'));
        $encoded .= $this->encodeUint256((string) ($piC[1] ?? '0'));

        // Encode public inputs
        foreach ($proof->publicInputs as $input) {
            $encoded .= $this->encodeUint256((string) $input);
        }

        return '0x' . $encoded;
    }

    /**
     * Encode a decimal string as a 32-byte (64-char) hex ABI uint256.
     * Uses bcmath to handle 256-bit field elements that exceed PHP int range.
     */
    private function encodeUint256(string $decimalValue): string
    {
        if (! is_numeric($decimalValue)) {
            return str_repeat('0', 64);
        }

        $hex = '';
        $value = $decimalValue;

        if (bccomp($value, '0') === 0) {
            return str_repeat('0', 64);
        }

        while (bccomp($value, '0') > 0) {
            $remainder = bcmod($value, '16');
            $hex = dechex((int) $remainder) . $hex;
            $value = bcdiv($value, '16', 0);
        }

        return str_pad($hex, 64, '0', STR_PAD_LEFT);
    }

    /**
     * Decode a boolean result from an eth_call response.
     */
    private function decodeBoolResult(string $hexResult): bool
    {
        // Remove 0x prefix and leading zeros
        $cleaned = ltrim(substr($hexResult, 2), '0');

        return $cleaned === '1';
    }

    /**
     * Estimate gas for a contract call.
     */
    private function estimateGas(string $rpcUrl, string $to, string $data): int
    {
        $response = Http::timeout(15)
            ->post($rpcUrl, [
                'jsonrpc' => '2.0',
                'id'      => 1,
                'method'  => 'eth_estimateGas',
                'params'  => [
                    ['to' => $to, 'data' => $data],
                ],
            ]);

        if ($response->successful() && ! isset($response->json()['error'])) {
            $gasHex = (string) ($response->json()['result'] ?? '0x0');

            return (int) hexdec(ltrim($gasHex, '0x'));
        }

        // Fallback: typical Groth16 verification gas cost
        return 230000;
    }

    /**
     * Detect chain name from RPC URL.
     */
    private function detectChain(string $rpcUrl): string
    {
        return match (true) {
            str_contains($rpcUrl, 'mainnet')  => 'ethereum',
            str_contains($rpcUrl, 'polygon')  => 'polygon',
            str_contains($rpcUrl, 'arbitrum') => 'arbitrum',
            str_contains($rpcUrl, 'base')     => 'base',
            str_contains($rpcUrl, 'sepolia')  => 'sepolia',
            str_contains($rpcUrl, 'goerli')   => 'goerli',
            default                           => 'unknown',
        };
    }

    /**
     * Fallback verification using the SnarkJS prover when no RPC is configured.
     *
     * @return array{verified: bool, tx_hash: string|null, gas_used: int, chain: string}
     */
    private function fallbackVerification(ZkProof $proof): array
    {
        // Use local snarkjs verification as fallback
        $snarkjs = app(SnarkjsProverService::class);
        $verified = $snarkjs->verifyProof($proof);

        return [
            'verified' => $verified,
            'tx_hash'  => null,
            'gas_used' => 0,
            'chain'    => 'local',
        ];
    }
}
