<?php

declare(strict_types=1);

namespace App\Domain\CardSubscriptions\Enums;

enum CardErrorCode: string
{
    case USER_NOT_ACTIVE = 'USER_NOT_ACTIVE';
    case FULL_KYC_REQUIRED = 'FULL_KYC_REQUIRED';
    case HIGH_RISK_USER = 'HIGH_RISK_USER';
    case SUBSCRIPTION_REQUIRED = 'SUBSCRIPTION_REQUIRED';
    case SUBSCRIPTION_NOT_ACTIVE = 'SUBSCRIPTION_NOT_ACTIVE';
    case PLAN_DOES_NOT_ALLOW_VIRTUAL_CARD = 'PLAN_DOES_NOT_ALLOW_VIRTUAL_CARD';
    case PLAN_DOES_NOT_ALLOW_PHYSICAL_CARD = 'PLAN_DOES_NOT_ALLOW_PHYSICAL_CARD';
    case PLAN_DOES_NOT_ALLOW_ATM = 'PLAN_DOES_NOT_ALLOW_ATM';
    case VIRTUAL_CARD_LIMIT_REACHED = 'VIRTUAL_CARD_LIMIT_REACHED';
    case PHYSICAL_CARD_LIMIT_REACHED = 'PHYSICAL_CARD_LIMIT_REACHED';
    case MONTHLY_CREATION_LIMIT_REACHED = 'MONTHLY_CREATION_LIMIT_REACHED';
    case STEP_UP_AUTH_REQUIRED = 'STEP_UP_AUTH_REQUIRED';
    case PROCESSOR_CARD_CREATION_FAILED = 'PROCESSOR_CARD_CREATION_FAILED';
    case INSUFFICIENT_WALLET_BALANCE = 'INSUFFICIENT_WALLET_BALANCE';
    case PLAN_NOT_AVAILABLE = 'PLAN_NOT_AVAILABLE';
    case PLAN_NOT_ELIGIBLE_FOR_USER = 'PLAN_NOT_ELIGIBLE_FOR_USER';
    case GUARDIAN_APPROVAL_REQUIRED = 'GUARDIAN_APPROVAL_REQUIRED';
    case MINOR_REQUEST_PENDING = 'MINOR_REQUEST_PENDING';
    case DUPLICATE_SUBSCRIPTION = 'DUPLICATE_SUBSCRIPTION';
    case CARD_NOT_FOUND = 'CARD_NOT_FOUND';
    case ADMIN_FROZEN_CARD = 'ADMIN_FROZEN_CARD';
    case IDEMPOTENCY_KEY_REUSE_MISMATCH = 'IDEMPOTENCY_KEY_REUSE_MISMATCH';
    case PROCESSOR_UNAVAILABLE = 'PROCESSOR_UNAVAILABLE';
    case ATM_NOT_ALLOWED = 'ATM_NOT_ALLOWED';
    case INTERNATIONAL_DISABLED = 'INTERNATIONAL_DISABLED';
    case ONLINE_DISABLED = 'ONLINE_DISABLED';
    case MCC_BLOCKED = 'MCC_BLOCKED';
    case HIGH_RISK_TRANSACTION = 'HIGH_RISK_TRANSACTION';
    case INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS';
    case PER_TRANSACTION_LIMIT_EXCEEDED = 'PER_TRANSACTION_LIMIT_EXCEEDED';
    case DAILY_LIMIT_EXCEEDED = 'DAILY_LIMIT_EXCEEDED';
    case MONTHLY_LIMIT_EXCEEDED = 'MONTHLY_LIMIT_EXCEEDED';
    case ATM_LIMIT_EXCEEDED = 'ATM_LIMIT_EXCEEDED';
    case MINOR_CARD_LIMIT_EXCEEDED = 'MINOR_CARD_LIMIT_EXCEEDED';
    case CARD_NOT_ACTIVE = 'CARD_NOT_ACTIVE';
    case SUBSCRIPTION_INACTIVE = 'SUBSCRIPTION_INACTIVE';
}
