<?php

declare(strict_types=1);

namespace App\Domain\CardSubscriptions\Enums;

enum DeclineReason: string
{
    case CARD_NOT_FOUND = 'CARD_NOT_FOUND';
    case CARD_NOT_ACTIVE = 'CARD_NOT_ACTIVE';
    case USER_NOT_ACTIVE = 'USER_NOT_ACTIVE';
    case SUBSCRIPTION_INACTIVE = 'SUBSCRIPTION_INACTIVE';
    case INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS';
    case PER_TRANSACTION_LIMIT_EXCEEDED = 'PER_TRANSACTION_LIMIT_EXCEEDED';
    case DAILY_LIMIT_EXCEEDED = 'DAILY_LIMIT_EXCEEDED';
    case MONTHLY_LIMIT_EXCEEDED = 'MONTHLY_LIMIT_EXCEEDED';
    case ATM_NOT_ALLOWED = 'ATM_NOT_ALLOWED';
    case ATM_LIMIT_EXCEEDED = 'ATM_LIMIT_EXCEEDED';
    case INTERNATIONAL_DISABLED = 'INTERNATIONAL_DISABLED';
    case ONLINE_DISABLED = 'ONLINE_DISABLED';
    case MCC_BLOCKED = 'MCC_BLOCKED';
    case HIGH_RISK_TRANSACTION = 'HIGH_RISK_TRANSACTION';
    case PROCESSOR_ERROR = 'PROCESSOR_ERROR';
    case MINOR_CARD_LIMIT_EXCEEDED = 'MINOR_CARD_LIMIT_EXCEEDED';
    case GUARDIAN_NOT_APPROVED = 'GUARDIAN_NOT_APPROVED';
}
